name: infra-insalanfr
services:
  backend:
    build: ./backend
    image: insalan/backend
    restart: unless-stopped
    environment:
      WEBSITE_HOST: ${WEBSITE_HOST}
      HTTP_PROTOCOL: ${PROTOCOL}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASS: ${MONGODB_PASS}
      NGINX_PORT: ${EXTERNAL_NGINX_PORT}
      MAIL_AUTH: ${MAIL_AUTH}
      STATIC_ROOT: ${BACKEND_STATIC_ROOT}
      MEDIA_ROOT: ${BACKEND_MEDIA_ROOT}
      SUPERUSER_USER: ${SUPERUSER_USER}
      SUPERUSER_PASS: ${SUPERUSER_PASS}
      DJANGO_SECRET: ${BACKEND_DJANGO_SECRET}
      SESSION_COOKIE_AGE: ${SESSION_COOKIE_AGE}
      HELLOASSO_HOSTNAME: ${HELLOASSO_HOSTNAME}
      HELLOASSO_ORGANIZATION_SLUG: ${HELLOASSO_ORG_SLUG}
      HELLOASSO_CLIENT_ID: ${HELLOASSO_CLIENT_ID}
      HELLOASSO_CLIENT_SECRET: ${HELLOASSO_CLIENT_SECRET}
      HELLOASSO_BACK_URL: ${HELLOASSO_BACK_URL}
      HELLOASSO_RETURN_URL: ${HELLOASSO_RETURN_URL}
      HELLOASSO_ERROR_URL: ${HELLOASSO_ERROR_URL}
      DEV: 0
    volumes:
      - ./volumes/prod/backend:/app/v1
    expose:
      - 8000
    networks:
      - backend
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_SUPERUSER}
      POSTGRES_PASSWORD: ${DB_SUPERPASS}
      INSALAN_USERNAME: ${DB_USER}
      INSALAN_PASSWORD: ${DB_PASS}
      INSALAN_DATABASE: ${DB_NAME}
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./volumes/prod/postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend

  mongo-db:
    image: mongo
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${DB_SUPERUSER}
        MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    expose:
      - 5433
    networks:
      - backend

  frontend:
    build: ./frontend
    image: insalan/frontend
    environment:
      - VITE_API_URL=${PROTOCOL}://api.${WEBSITE_HOST}/v${API_VERSION}
      - NODE_ENV=${FRONTEND_NODE_ENV}
      - VITE_WEBSITE_HOST=${WEBSITE_HOST}
      - VITE_SESSION_COOKIE_AGE=${SESSION_COOKIE_AGE}
    volumes:
      - ./volumes/prod/frontend:/dist
    networks:
      - backend
  
  nginx:
    image: nginx
    restart: unless-stopped
    environment:
      - NGINX_HOST=${WEBSITE_HOST}
      - NGINX_PORT=80
      - STATIC_ROOT=${BACKEND_STATIC_ROOT}
      - MEDIA_ROOT=${BACKEND_MEDIA_ROOT}
    ports:
      - "${PROD_NGINX_PORT}:80"
    volumes:
      - ./volumes/prod/backend:/usr/share/nginx/html
      - ./volumes/prod/frontend:/usr/share/nginx/html/frontend
      - ./nginx/templates/prod:/etc/nginx/templates:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/prod/nginx/logs:/var/log/nginx

    networks:
      - backend
    depends_on:
      - backend
      - frontend

networks:
  backend:
