name: analytics-insalanfr
services:
  telegraf:
    image: telegraf:1.33
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./volumes/prod/nginx/logs:/var/log/nginx:ro
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    depends_on:
      - influxdb
    networks:
      - analytics
    deploy:
      resources:
        limits:
          cpus: '0.50'  # Limit to 50% of a single CPU core
          memory: '256M'  # Limit to 256MB of memory

  influxdb:
    image: influxdb:1.8-alpine
    volumes:
      - ./volumes/prod/influxdb:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    environment:
      - INFLUXDB_DB=nginx_logs
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_LOGGING_LEVEL=error
    expose:
      - 8086
    networks:
      - analytics

  grafana:
    image: grafana/grafana:11.5.2
    # Run as root user to prevent file permission issues
    user: "0"
    volumes:
      - ./volumes/prod/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_LOG_LEVEL=error
    ports:
      - "3000:3000"
    networks:
      - analytics
    depends_on:
      - influxdb

networks:
  analytics: