name: infra-insalanfr
services:
  backend:
    build: ./backend
    image: insalan/backend
    restart: unless-stopped
    environment:
      WEBSITE_HOST: ${WEBSITE_HOST}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SSL: ${MAIL_SSL}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_PASS: ${MAIL_PASS}
      SUPERUSER_USER: ${SUPERUSER_USER}
      SUPERUSER_PASS: ${SUPERUSER_PASS}
      STATIC_ROOT: ${BACKEND_STATIC_ROOT}
      DJANGO_SECRET: ${BACKEND_DJANGO_SECRET}
      DEV: 0
    volumes:
      - ./volumes/prod/backend/static:${BACKEND_STATIC_ROOT}
    expose:
      - 8000
    networks:
      - backend
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_SUPERUSER}
      POSTGRES_PASSWORD: ${DB_SUPERPASS}
      INSALAN_USERNAME: ${DB_USER}
      INSALAN_PASSWORD: ${DB_PASS}
      INSALAN_DATABASE: ${DB_NAME}
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./volumes/prod/postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend

  frontend:
    build: ./frontend
    image: insalan/frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=api.${WEBSITE_HOST}
      - NODE_ENV=${FRONTEND_NODE_ENV}
      - VITE_WEBSITE_HOST=${WEBSITE_HOST}
    volumes:
      - ./volumes/prod/frontend:/dist
    networks:
      - backend
  
  nginx:
    image: nginx
    restart: unless-stopped
    environment:
      - NGINX_HOST=${WEBSITE_HOST}
      - NGINX_PORT=80
      - STATIC_ROOT=${BACKEND_STATIC_ROOT}
    ports:
      - "${PROD_NGINX_PORT}:80"
    volumes:
      - ./volumes/prod/backend/static:/usr/share/nginx/html/static:ro
      - ./volumes/prod/frontend:/usr/share/nginx/html/frontend
      - ./nginx/templates/prod:/etc/nginx/templates:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/prod/nginx/logs:/var/log/nginx

    networks:
      - backend
    depends_on:
      - backend
      - frontend

networks:
  backend:
